server:
  port: 8080

spring:
  application:
    name: MongoFullTextSearch
  data:
    mongodb:
      host: localhost
      username: root
      password: example
      port: 27017
      database: text_search
      authentication-database: admin